# syntax=docker/dockerfile:1.7

FROM node:20-alpine AS builder
WORKDIR /app

ARG VITE_ADMIN_PASSWORD
ARG VITE_GUEST_PASSWORD
ARG VITE_S3_ENDPOINT
ARG VITE_S3_ACCESS_KEY_ID
ARG VITE_S3_SECRET_ACCESS_KEY
ARG VITE_S3_REGION
ARG VITE_S3_BUCKET
ARG VITE_TELEGRAM_BOT_TOKEN
ARG VITE_TELEGRAM_CHAT_ID

ENV VITE_ADMIN_PASSWORD=$VITE_ADMIN_PASSWORD \
    VITE_GUEST_PASSWORD=$VITE_GUEST_PASSWORD \
    VITE_S3_ENDPOINT=$VITE_S3_ENDPOINT \
    VITE_S3_ACCESS_KEY_ID=$VITE_S3_ACCESS_KEY_ID \
    VITE_S3_SECRET_ACCESS_KEY=$VITE_S3_SECRET_ACCESS_KEY \
    VITE_S3_REGION=$VITE_S3_REGION \
    VITE_S3_BUCKET=$VITE_S3_BUCKET \
    VITE_TELEGRAM_BOT_TOKEN=$VITE_TELEGRAM_BOT_TOKEN \
    VITE_TELEGRAM_CHAT_ID=$VITE_TELEGRAM_CHAT_ID

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
